---
- hosts: all
  tasks:
  - name: Create files for test results 1
    copy:
      content: "{{ 'test' | a_filter }}"
      dest: /tmp/result1
  - name: Create files for test results 2
    copy:
      content: "{{ 'test' | another_filter('the','filters') }}"
      dest: /tmp/result2
  roles:
    - role: jinja2-ansible-test
