---
- name: Converge
  hosts: all
  gather_facts: False
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: True
      changed_when: False
    - name: Create files for test results 1
      copy:
        content: "{{ 'test' | a_filter }}"
        dest: /tmp/result1
    - name: Create files for test results 2
      copy:
        content: "{{ 'test' | b_filter('the','filters') }}"
        dest: /tmp/result2
    - name: Demostrate permutations filter
      copy:
        content: "{{ [1,2,3,4,5] | permutations(2) | list }}"
        dest: /tmp/result3
    - name: Demostrate combinations filter
      copy:
        content: "{{ [1,2,3,4,5] | combinations(2) | list }}"
        dest: /tmp/result4
    - name: Demostrate zip filter
      copy:
        content: "{{ [1,2,3,4,5] | zip(['a','b','c','d','e','f']) | list }}"
        dest: /tmp/result5
    - name: set a variable for inclusion
      set_fact: my_groups='all'
    - name: Demonstrate the groups variables
      copy:
        content: "{{ groups[my_groups] | list }}"
        dest: /tmp/result6
    - name: Demonstrate the groups variables
      vars:
        site_data_mountpoints:
          - /tmp/a
          - /tmp/b
        platform_public_kafka_cluster_kube_namespace: 'default'
        platform_public_kafka_cluster_name: 'public_kafka'
      copy:
        content: "{{ site_data_mountpoints | map('regex_replace', '(.*)', '\\1/platform/'+platform_public_kafka_cluster_kube_namespace+'/kafka-cluster/'+platform_public_kafka_cluster_name) | list }}"
        dest: /tmp/result7

- name: Converge
  hosts: all
  roles:
    - role: jinja2-ansible-test
